apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webook-mysql-live-claim
  labels:
    app: webook-mysql-live-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi